version: '3.7'

services:

  redis:
    image: 'redis:5.0.5'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "src.app:flask_app"
    env_file:
      - '.env'
    volumes:
      - '.:/flask_celery_redis'
    ports:
      - '8000:8000'

  celery:
    build: .
    command: celery worker -A wsgi_app.celery --loglevel=info --pool=solo
    env_file:
      - '.env'
    volumes:
      - '.:/flask_celery_redis'

volumes:
  redis:
